desafiourbe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('incorporador.urls', namespace="incorporador")),
] 


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

incorporador/urls.py
from django.urls import path, reverse_lazy
from .views import Homepage, Homeincorporador, Detalhesincorporador, Pesquisaincorporador, Paginaperfil, Criarconta
from django.contrib.auth import views as auth_view #view padrao do django para login/logout, muda o nome para nao confundir

app_name = 'incorporador'

urlpatterns = [
    path("", Homepage.as_view(), name="homepage"),
    path("incorporadora/", Homeincorporador.as_view(), name="homeincorporador"),
    path("incorporadora/<int:pk>", Detalhesincorporador.as_view(), name="detalhesincorporador"),
    path("pesquisa/", Pesquisaincorporador.as_view(), name="pesquisa"),
    path("login/", auth_view.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", auth_view.LogoutView.as_view(template_name="logout.html"), name="logout"),
    path("editarperfil/<int:pk>", Paginaperfil.as_view(), name="editarperfil"),
    path("criarconta/", Criarconta.as_view(), name="criarconta"),
    path("mudarsenha/", auth_view.PasswordChangeView.as_view(template_name="editarperfil.html", success_url=reverse_lazy("incorporador:homepage")), name="mudarsenha"),
] 

incorporador/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
# Create your models here.

#("armazenar no bd", "aparecer pro usuario")
LISTA_CATEGORIAS = (
    ("COMERCIAL", "Comercial"),
    ("RESIDENCIAL", "Residencial"),
    ("OUTROS", "Outros"),
)

# criar o incorporador
class Incorporador(models.Model):
    titulo = models.CharField(max_length=100) 
    thumb = models.ImageField(upload_to='thumb_incorporadores')
    descricao = models.TextField(max_length=2000)
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.titulo
  
class Usuario(AbstractUser):
    incorporadoras_vistas = models.ManyToManyField("Incorporador")

# criar os investimentos 

incorporador/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms


class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

incorporador/views.py
from django.shortcuts import render, redirect, reverse
from .models import Incorporador, Usuario
from .forms import CriarContaForm
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin # passo isso quando quero bloquear views
                                                          # o LoginRequiredMixin vem antes da classe do objeto
                                                          # class ... (LoginRequiredMixin, TemplateView):

# Create your views here.

class Homepage(TemplateView):
    template_name = "homepage.html"

class Homeincorporador(ListView):
    template_name = "homeincorporador.html"
    model = Incorporador #object list do modelo

class Detalhesincorporador(DetailView):
    template_name = "detalhesincorporador.html"
    model = Incorporador #object -> 1 item do modelo

    def get(self, request, *args, **kwargs): #contabilizando vizualizacoes
        incorporador = self.get_object()
        incorporador.visualizacoes += 1
        incorporador.save()
        usuario = request.user
        usuario.incorporadoras_vistas.add(incorporador) #metodos que relacionam com o banco de dados (add e nao append)
        return super().get(request, *args,**kwargs) #redireciona o usuario para a url final

    def get_context_data(self, **kwargs):
        context = super(Detalhesincorporador,self).get_context_data(**kwargs)
        #filtrando tabela de incorporador para a mesma categoria
        incorporador_relacionado = Incorporador.objects.filter(categoria=self.get_object().categoria)
        context["incorporador_relacionado"] = incorporador_relacionado
        return context
    

class Pesquisaincorporador(ListView):
    template_name = "pesquisa.html"
    model = Incorporador 

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            object_list = Incorporador.objects.filter(descricao__icontains=termo_pesquisa)
            return object_list
        else:
            return None


class Paginaperfil(LoginRequiredMixin,UpdateView):
    template_name = "editarperfil.html"
    model = Usuario 
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse ('incorporador:homepage')

class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse ('incorporador:login')

incorporador/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Criar conta
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background.jpeg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-shine text-center flex items-center flex-col">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                {{form|crispy}}
            </fieldset>
            <button class="bg-blue-500 text-lg py-1 my-2 px-3 font-medium hover:bg-blue-700 text-shite md:font-normal rounded-md" type="submit">Criar Conta</button>
        </form>

    </div>
</header>
<footer class=" px-6 py-15 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2023</li>
        <li> Feito com Python (Django)</li>
        <li>Nelson</li>
    </ul>
</footer>
{% endblock %}

incorporador/templates/detalhesincorporador.html
{% extends 'base.html' %}
{% block titulo %}
Incorporador
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{object.thumb.url}}');">
        <div>
            <h2 class="text-6xl text-black font-semibold my-4">
                {{object.titulo}}
            </h2>
            <p class=" w-11/12 text-black md:w-5/12 font-medium my-4">
                {{object.descricao|slice:":200"}}... 
            </p>
            <div class="flex my-4">
                <a href="{% url 'incorporador:detalhesincorporador' incorporador.id %}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Conheça mais
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section> 
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-black text-3xl font-medium">
                Sobre a incorporadora 
            </h2>
            <br>
            <br>
            <div class="flex justify-left  items-center min-w-full  movie_lis">
                <p class="text-gray-100 text-black text-justify text-lg">
                    {{object.descricao}}
                </p>
            </div>
        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-black text-2xl font-medium">
                Incorporadoras relacionadas
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for incorporador in incorporador_relacionado %} 
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'incorporador:detalhesincorporador' incorporador.id %}">
                        <img src="{{incorporador.thumb.url}}" class="object-cover w-full h-full " alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    
</main>  
{% endblock %}

incorporador/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Editar Perfil
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background.jpeg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-shine text-center flex items-center flex-col">
        <h2 class="text-2xl">{{user.username}}</h2>
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
            {{ form|crispy }}
            </fieldset>
            <button class="bg-blue-500 text-lg py-1 my-2 px-3 font-medium hover:bg-blue-700 text-shite md:font-normal rounded-md" type="submit">Editar Perfil</button>
        </form>
        <small><a href="{% url 'incorporador:mudarsenha' %}">Quer mudar sua senha?</a></small>
    </div>
</header>
<footer class=" px-6 py-15 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2023</li>
        <li> Feito com Python (Django)</li>
        <li>Nelson</li>
    </ul>
</footer>
{% endblock %}

incorporador/templates/homeincorporador.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}
Incorporadora 
{% endblock %}

{% block head %}
<style>
    $itemGrow: 1.2;
$duration: 250ms;

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
}

h1 {
  font-family: Arial;
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(3,100%);
  overflow:hidden;
  scroll-behavior: smooth;

  section {
    width: 100%;
    position: relative;
    display: grid;
    grid-template-columns: repeat(5, auto);
    margin: 20px 0;
    
    .item {
      padding: 0 2px;
      transition: $duration all;
      
      &:hover { 
        margin: 0 40px;
        transform: scale(1.2);
      }
      
    }
    
    a {
      position: absolute;
      color: #fff;
      text-decoration: none;
      font-size: 6em;
      background:rgb(0,0,0);
      width: 80px;
      padding: 20px;
      text-align: center;
      z-index: 1;
      
      &:nth-of-type(1) {
        top:0; bottom:0; left:0;
        background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      &:nth-of-type(2) {
        top:0; bottom:0; right: 0;
        background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      
    }
    
  }
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
  a.arrow__btn {
    display:none;
  }
}
</style>
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{incorporador_destaque.thumb.url}}');">
        <div>
            <h2 class="text-6xl font-semibold text-neutral-800 my-4">
                {{incorporador_destaque.titulo}}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium bg-white/[0.25] rounded-md text-neutral-800 my-4">
                {{incorporador_destaque.descricao}}
            </p>
            <div class="flex my-4">
                <a href="{% url 'incorporador:detalhesincorporador' incorporador_destaque.id %}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium " >
                            Saiba mais
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section> 


    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-neutral-800 text-2xl font-medium">
                Novos incorporadores 
            </h2>
            <div class="wrapper">
              <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                {% for incorporador in incorporador_popular %}
                {% if forloop.counter < 5 %}
                  <div class="item h-64 w-1/4 m-4">
                      <a href="{% url 'incorporador:detalhesincorporador' incorporador.id %}">
                        <img src="{{incorporador.thumb.url}}" class="rounded-md w-full h-full object-cover">
                      </a>
                  </div>
                {% endif %}
                {% endfor %}
                    <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
              </section>
              {% if incorporador_popular|length > 4 %} 
                  <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                    {% for incorporador in incorporador_popular %}
                    {% if forloop.counter > 4 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'incorporador:detalhesincorporador' incorporador.id %}">
                            <img src="{{incorporador.thumb.url}}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                    {% endif %}
                    {% endfor %}
                    <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                  </section>
              {% endif %}
            </div>


        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-neutral-800 text-2xl font-medium">
                Em alta 
            </h2>
            <div class="wrapper">
              <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                {% for incorporador in incorporador_popular %}
                {% if forloop.counter < 5 %}
                  <div class="item h-64 w-1/4 m-4">
                      <a href="{% url 'incorporador:detalhesincorporador' incorporador.id %}">
                        <img src="{{incorporador.thumb.url}}" class="rounded-md w-full h-full object-cover">
                      </a>
                  </div>
                {% endif %}
                {% endfor %}
                    <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
              </section>
              {% if incorporador_popular|length > 4 %} 
                  <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                    {% for incorporador in incorporador_popular %}
                    {% if forloop.counter > 4 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'incorporador:detalhesincorporador' incorporador.id %}">
                            <img src="{{incorporador.thumb.url}}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                    {% endif %}
                    {% endfor %}
                    <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                  </section>
              {% endif %}
            </div>


        </div>
    </section>
    <section class='bg-primary_black flex justify-center py-10'>
      <div class="p-8 w-10/12 relative" >
          <h2 class="text-neutral-800 text-2xl font-medium">
              Ver novamente 
          </h2>
          <div class="wrapper">
            <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
              <a href="#section2vistos" class="arrow__btn text-6xl page">‹</a>
              {% for incorporador in request.user.incorporadoras_vistas.all %}
              {% if forloop.counter < 5 %}
                <div class="item h-64 w-1/4 m-4">
                    <a href="{% url 'incorporador:detalhesincorporador' incorporador.id %}">
                      <img src="{{incorporador.thumb.url}}" class="rounded-md w-full h-full object-cover">
                    </a>
                </div>
              {% endif %}
              {% endfor %}
                  <a href="#section2vistos" class="arrow__btn text-6xl">›</a>
            </section>
            {% if request.user.incorporadoras_vistas.all|length > 4 %} 
                <section id="section2vistos" class="flex flex-nowrap items-center justify-center">
                  <a href="#section1vistos" class="arrow__btn text-6xl">‹</a>
                  {% for incorporador in request.user.incorporadoras_vistas.all %}
                  {% if forloop.counter > 4 %}
                    <div class="item h-64 w-1/4 m-4">
                        <a href="{% url 'incorporador:detalhesincorporador' incorporador.id %}">
                          <img src="{{incorporador.thumb.url}}" class="rounded-md w-full h-full object-cover">
                        </a>
                    </div>
                  {% endif %}
                  {% endfor %}
                  <a href="#section1vistos" class="arrow__btn text-6xl">›</a>
                </section>
            {% endif %}
          </div>


      </div>
  </section>

</main>
{% endblock %}

incorporador/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
HomePage Desafio URBE.ME
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-25 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background.jpeg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-grey-100 text-center flex items-center flex-col">

        <h1 class="font-semibold text-black text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
            A primeira empresa de crowdfunding imobiliário do Brasil.
        </h1>
        <br>
        <br>
        <br>
        <br>
        <br>
        <h3 class="font-semibold text-3xl text-black md:text-3xl py-5 text-center">
            Conheça nossos investimentos.
        </h3>
        <div class="w-full flex justify-center">
            <div class="flex justify-center items-center w-11/12 md:w-10/12">
                <form method="post" class="w-6/12 justify-center">
                    <div class="flex flex-col items-center">
                        <a href="{% url 'incorporador:homeincorporador' %}"
                    <button class="bg-blue-500 font-medium hover:bg-blue-700 text-white md:font-normal flex justify-center items-center font-bold py-2 px-4 rounded md:text-2xl" type="submit">
                        <span>
                            Clique aqui
                        </span>
                        <ion-icon name="chevron-forward-outline" class="text-xl"></ion-icon>
                    </button>
                         </a>
                    </div>
                </form>
                </a>
            </div>
        </div>

    </div>
</header>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Projetos
        </h2>
        <h5 class="md:text-xl text-justify text-lg">
            Através da URBE.ME, você tem acesso a um mercado antes acessível apenas aos grandes investidores: a etapa mais rentável do mercado imobiliário que é a incorporação do empreendimento.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/projetos.png' %}" class="w-8/12" alt="">
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class='md:w-1/2 flex justify-center items-center '>
        <img src="{% static 'images/rentabilidade.png' %}" class="w-8/12" alt="">
    </div>

    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            No que você está investindo
        </h2>
        <h5 class="md:text-xl text-justify text-lg">
            Ao investir em algum empreendimento via URBE.ME, o investidor adquire um título de dívida chamado Cédula de Crédito Bancário (CCB) da incorporadora que contempla uma rentabilidade pré-fixada (rentabilidade mínima da operação) e ainda o direito a uma participação percentual no VGV (Valor Geral de Vendas) do empreendimento. Assim, os investidores passam a ser credores do projeto.
        </h5>
    </div>
    
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Sobre nós
        </h2>
        <h5 class="md:text-xl text-justify text-lg">
            A URBE.ME é uma plataforma de investimento coletivo online voltada para o setor imobiliário. Surgimos em 2015 com o intuito de simplificar, desburocratizar e democratizar o investimento em imóveis. Através da nossa plataforma, você conta com toda a expertise do nosso time de análise e curadoria dos projetos, podendo tomar a decisão de investir em questão de minutos e 100% online com um aporte de capital a partir de R$ 1.000,00.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/sobre.png' %}" class="w-8/12" alt="">
    </div>
</section>
<footer class=" px-6 py-15 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2023</li>
        <li> Feito com Python (Django)</li>
        <li>Nelson</li>
    </ul>
</footer>

{% endblock %}

incorporador/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Fazer Login
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background.jpeg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-shite text-center flex items-center flex-col">
        <form method="post">
            {% csrf_token %} 
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Faça Login para continuar</legend>
                {{ form|crispy }}
            </fieldset>
            <button class="bg-blue-500 text-lg py-1 my-2 px-3 font-medium hover:bg-blue-700 text-shite md:font-normal rounded-md " type="submit">Fazer Login</button>
        </form>
        <br>
        <small>
            Não tem uma conta ainda? <p><a href="{% url 'incorporador:criarconta'%}">Clique aqui para criar uma conta</a></p>
        </small>
    </div>
</header>
<footer class=" px-6 py-15 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2023</li>
        <li> Feito com Python (Django)</li>
        <li>Nelson</li>
    </ul>
</footer>

{% endblock %}

incorporador/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Logout
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-25 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background.jpeg' %}');">
    <div class="font-semibold text-black text-2xl md:text-4xl w-10/12 md:w-3/4 text-center">
        <br>
        <br>
        <br>
        <br>
        <br>
        <h2>Você saiu da sua conta</h2>
        <br>
        <div class="flex flex-nowrap justify-center space-x-5 p-5">
        <a href="{% url 'incorporador:login' %}"><button class="bg-blue-500 font-medium hover:bg-blue-700 text-shite md:font-normal flex justify-center items-center font-bold py-2 px-4 rounded md:text-base">Fazer Login</button></a>
        <a href="{% url 'incorporador:criarconta' %}"><button class="bg-blue-500 font-medium hover:bg-blue-700 text-shite md:font-normal flex justify-center items-center font-bold py-2 px-4 rounded md:text-base">Criar uma Conta</button></a>
        </div>
    </div>
</header>

<footer class=" px-6 py-15 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2023</li>
        <li> Feito com Python (Django)</li>
        <li>Nelson</li>
    </ul>
</footer>
{% endblock %}

incorporador/templates/pesquisa.html
{% extends 'base.html' %}

{% block titulo %}
Pesquisa de incorporadoras
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Resultados da Busca
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for incorporador in object_list %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'incorporador:detalhesincorporador' incorporador.pk %}">
                        <img src="{{incorporador.thumb.url}}" class="object-cover w-full h-full " alt="">
                    </a>
                    </div>
                {% endfor %}    
            </div>


        </div>
    </section>
</main>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>
        {% block titulo %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>

    {% block head %}
    {% endblock %}

    <meta charset="utf-8">
  </head>
  <body class="bg-slate-300 text-neutral-800 font-primary">
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}


    <script>
      const nav = document.querySelector('nav')

      document.addEventListener("scroll",e=>{
          
          if(scrollY>500){
              if(scrollY>window.innerHeight){
              nav.classList.add('invisible')
          }else{
              nav.classList.add('bg-inherit')
              nav.classList.remove('invisible')
          }
          }else{
              nav.classList.remove('bg-inherit')
              nav.classList.remove('invisible')
          }
      })
    </script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

templates/navbar.html
{% load static %}

<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50"> 
    <div class="w-6/12"> 
        <a href="/">
            <img class="w-3/12" src="{% static 'images/logo2.png' %}">
        </a>
    </div>

    <div class="w-6/12 flex flex-nowrap justify-end">
        <div class="mr-2">
            <form method="get" action="{% url 'incorporador:pesquisa' %}">
                <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value ="{{request.GET.query}}" placeholder="Pesquisar..."> 
            </form>
        </div>

        <div class="mr-2">
            {% if user.is_authenticated%}
            <a href="{% url 'incorporador:logout' %}"> 
                <button class="bg-blue-600 text-shite py-1 px-3 rounded-md"> 
                    Sair
                </button>
            </a>
            {% if user.is_authenticated %}
            <a href="{% url 'incorporador:editarperfil' request.user.id %}">
                <button class="bg-blue-600 text-shite py-1 px-3 rounded-md"> 
                    Editar Perfil
                </button>
            {% endif %}
            </a>
            {% else %}
            <a href="{% url 'incorporador:login' %}"> 
                <button class="bg-blue-600 text-shite py-1 px-3 rounded-md"> 
                    Login
                </button>
            </a>
            {% endif %}
        </div>
    </div>

</nav>